# Utils

## Select variables that could be useful for alcohol and explanation
## Made use of character vector
selected_variables <-
  c(
    "DMDEDUC2" = "HighestEducationLevel",
    "DMDBORN4" = "CountryBorn",
    "DMDFMSIZ" = "NoPeopleFamily",
    "DMDMARTL" = "MartialStatus",
    "RIAGENDR" = "Gender",
    "RIDAGEYR" = "Age",
    "SXQ292" = "SexualOrientationM",
    "SXQ294" = "SexualOrientationF",
    "SXQ410" = "SexWithMenLast12m",
    "SXQ130" = "SexWithWomenLast12m",
    "SXQ753" = "HadHPV",
    "SXQ260" = "HadHerpes",
    "SXQ265" = "HadGenitalWarts",
    "SXQ270" = "HadGonorrhea",
    "SXQ272" = "HadChlamydia",
    "LBDHI" = "HadHIV",
    "MCQ380" = "ProblemsRememberingThingsLast30d",
    "DLQ040" = "DifficultyConcentrating",
    "MCQ084" = "MemoryLossLast12m",
    "BPQ020" = "Hypertension",
    "MCQ080" = "Overweight",
    "MCQ203" = "HadJaundice",
    "HUD080" = "DaysInHospitalLast12m",
    "PAD660" = "TimeVigorousActivitiesPerDay",
    "CSQ240" = "HadLostConcientiousness",
    "DPQ020" = "FeelDownDepressedLast2W",
    "DPQ070" = "ProblemsConcentratingLast2w",
    "DPQ090" = "ThoughtSuicideLast2w",
    "SLD010H" = "SleepHoursWorkdays",
    "OCQ210" = "GreaterEqual35HoursWorkPerWeek",
    "IND235" = "MonthlyFamilyIncome",
    "INDFMMPI" = "FamilyPovertyIndex",
    "SMD641" = "SmokedCigsLast30d",
    "DUQ230" = "MarijuanaLast30d",
    "DUQ280" = "CocaineLast30d",
    "DUQ320" = "HeroineLast30d",
    "DUQ360" = "MethanfetamineLast30d",
    "OCQ180" = "HoursWorkPerWeek",
    "SMQ866" = "SpendTimeBar7d",
    "ALQ160" = "AlcoholDrink5Last30d",
    "ALQ120Q" = "AlcoholAmountAvgPerMonth",
    "ALQ120U" = "AlcoholAmountUnitPerMonth"
  )
